/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/N3fqOYt4mZ6
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export default function NewJob() {
  return (
    <div className="w-full max-w-4xl mx-auto p-6 sm:p-8 md:p-10">
      <div className="flex flex-col gap-8">
        <div>
          <h1 className="text-3xl font-bold">Job Description Manager</h1>
          <p className="text-muted-foreground">Create and manage detailed job postings for your company.</p>
        </div>
        <Card>
          <CardHeader>
            <CardTitle>Add New Job Posting</CardTitle>
            <CardDescription>Fill out the form below to create a new job description.</CardDescription>
          </CardHeader>
          <CardContent>
            <form className="grid gap-6">
              <div className="grid grid-cols-2 gap-4">
                <div className="grid gap-2">
                  <Label htmlFor="job-title">Job Title</Label>
                  <Input id="job-title" placeholder="Software Engineer" />
                </div>
                <div className="grid gap-2">
                  <Label htmlFor="job-type">Job Type</Label>
                  <Select id="job-type">
                    <SelectTrigger>
                      <SelectValue placeholder="Select job type" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="full-time">Full-Time</SelectItem>
                      <SelectItem value="part-time">Part-Time</SelectItem>
                      <SelectItem value="contract">Contract</SelectItem>
                      <SelectItem value="internship">Internship</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>
              <div className="grid gap-2">
                <Label htmlFor="job-description">Job Description</Label>
                <Textarea
                  id="job-description"
                  placeholder="Describe the responsibilities and requirements for this role."
                  rows={6}
                />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="required-skills">Required Skills</Label>
                <div className="flex flex-wrap gap-2">
                  <Input id="required-skills" placeholder="Add a skill" className="flex-1" />
                  <Button variant="outline" size="icon">
                    <PlusIcon className="h-5 w-5" />
                    <span className="sr-only">Add Skill</span>
                  </Button>
                </div>
                <div className="grid gap-2">
                  <div className="flex items-center justify-between">
                    <span>JavaScript</span>
                    <Button variant="outline" size="icon" className="text-red-500">
                      <TrashIcon className="h-5 w-5" />
                      <span className="sr-only">Remove Skill</span>
                    </Button>
                  </div>
                  <div className="flex items-center justify-between">
                    <span>React</span>
                    <Button variant="outline" size="icon" className="text-red-500">
                      <TrashIcon className="h-5 w-5" />
                      <span className="sr-only">Remove Skill</span>
                    </Button>
                  </div>
                </div>
              </div>
              <div className="grid gap-2">
                <Label htmlFor="required-qualifications">Required Qualifications</Label>
                <Textarea
                  id="required-qualifications"
                  placeholder="List the required qualifications for this role."
                  rows={3}
                />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="additional-details">Additional Details</Label>
                <Textarea
                  id="additional-details"
                  placeholder="Add any other relevant details about this job posting."
                  rows={3}
                />
              </div>
            </form>
          </CardContent>
          <CardFooter>
            <Button type="submit" className="ml-auto">
              Save Job Posting
            </Button>
          </CardFooter>
        </Card>
      </div>
    </div>
  )
}

function PlusIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}


function TrashIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 6h18" />
      <path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6" />
      <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2" />
    </svg>
  )
}


function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
